export const GET_RECIPES = "GET_RECIPES";
export const GET_DIETS = "GET_DIETS";
export const SEARCH_RECIPE = "SEARCH_RECIPE";
export const RESET_RECIPES = "RESET_RECIPES";
export const FILTER_DIETS = "FILTER_DIETS";
export const SORT_BY_ALPHABETICAL = "SORT_BY_ALPHABETICAL";
